allowCompoundWords: true
dictionaries:
  - cpp
  - csharp
  - dotnet
  - en-gb
  - en-us
  - fsharp
enableGlobDot: true
features:
  weighted-suggestions: true
globRoot: ${cwd}
id: kurone-kito
language: en,ja
ignorePaths:
  - .git
  - .github/CODE_OF_CONDUCT.*
  - .vscode/extensions.json
  - Assets/UdonSharp
  - Assets/XR
  - cspell.config.yml
  - package.json
  - Packages/com.*
  - Packages/dev.*
  - Packages/*.json
  - ProjectSettings
words:
  - kito
  - kuron√©
  - MSAA
  - occludee
  - udon
  - vrchat
  - vrcsdk
  - vrcui
useGitignore: true
version: '0.2'
